anything_but/config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :users

  resources :recommendations, only: [:create, :show]

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  get '/dashboard', to: 'users#show'


  get '/new-recommendation', to: 'recommendations#show'

  get '/activities', to: 'activities#index', as: 'activities'

  post "/user-liked-recommendation", to: 'recommendations#add_user_liked_activity'

end

anything_but/app/models/activity.rb
class Activity < ApplicationRecord
  has_many :activity_recommendations
  has_many :recommendations, through: :activity_recommendations
  validates :name, presence: true

  def self.search(term)
  where("name ILIKE ?", "%#{term}%")
  end
end

anything_but/app/models/activity_recommendation.rb
class ActivityRecommendation < ApplicationRecord
  belongs_to :recommendation
  belongs_to :activity
end

anything_but/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

anything_but/app/models/city.rb
class City < ApplicationRecord
  has_many :neighborhoods
end

anything_but/app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  has_many :recommendations
  belongs_to :city
end

anything_but/app/models/recommendation.rb
class Recommendation < ApplicationRecord
  has_many :activity_recommendations
  has_many :activities, through: :activity_recommendations
  has_many :user_recommendations
  has_many :users, through: :user_recommendations
  validates :name, presence: true
  # belongs_to :neighborhood

  @@filtered_array=[]
  @@previous_search=false

  def self.filtered_array=(array)
    @@filtered_array=array
  end

  def self.filtered_array
    @@filtered_array
  end

  def self.previous_search=(boolean)
    @@previous_search=boolean
  end

  def self.previous_search
    @@previous_search
  end
end

anything_but/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :user_recommendations
  has_many :recommendations, through: :user_recommendations

end

anything_but/app/models/user_activity.rb
class UserActivity < ApplicationRecord
  belongs_to :user
  belongs_to :activity
end

anything_but/app/models/user_recommendation.rb
class UserRecommendation < ApplicationRecord
  belongs_to :user
  belongs_to :recommendation
end

anything_but/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @activities = Activity.search(params[:term])
    render json: @activities.map(&:name).uniq
  end
  
end

anything_but/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user

  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user != nil
  end

  def authorize
    redirect_to '/' unless current_user
  end
end

anything_but/app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @neighborhoods = Neighborhoods.all
  end


  private

  def set_city
    @city = City.find(params[:id])
  end

end

anything_but/app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController


  def create
    neighborhood = Neighborhood.create(:name => 'apiData.name')
   
  end




end

anything_but/app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController



  def create
    yelp = Adapter::YelpWrapper.new
    nearby_recs=[]

    recommendation_array = yelp.initiate_api_req(params["latitude"], params["longitude"], yelp.categories)
    Recommendation.previous_search = true
    recommendation_array.flatten!.each do |one_rec|
      unless Recommendation.find_by(url: one_rec.url)
        rec=Recommendation.new(name:one_rec.name, url:one_rec.url)
        one_rec.categories.each do |category_array|
          if Activity.all.any?{|activity|activity.name==category_array[0]}
            rec.activities<<Activity.find_by(name:category_array[0])
            rec.save
          end
        end
      end
      nearby_recs<<Recommendation.all.find_by(url: one_rec.url)
      #array of all the activity recommendations nearby 
    end

    Recommendation.filtered_array=(yelp.filter_api(nearby_recs, params['doNotWant'])) #the filtered array of rec objects


    #we could make line 16 through 21 wrapped inside a SQL method?
    recommendation=Recommendation.filtered_array.sample
        respond_to do |f|
          f.json {
            render json: {name:recommendation.name, url:recommendation.url}
          }
        end
  end


  def show
    recommendation=Recommendation.filtered_array.sample
    respond_to do |f|
      f.json {
        render json: {name:recommendation.name, url:recommendation.url}
      }
    end
  end


  def add_user_liked_activity
    rec = Recommendation.find_by(url:params[:like_business_link])
    unless current_user.recommendations.any?{|recommendation| recommendation.url == rec.url}
      current_user.recommendations << rec
    end
  end



end

anything_but/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    #binding.pry
    @user = User.find_by_username(params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signin'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/"
  end

end

anything_but/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # binding.pry
    if @user.save
      session[:user_id] =  @user.id
      redirect_to '/'
    else
      redirect_to '/'
    end
  end

  def show

  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to dashboard_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.delete
    redirect_to '/signout'
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def set_user
    @user=current_user
  end

end

anything_but/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render "/welcome/welcome"
  end
end

anything_but/app/helpers/application_helper.rb
module ApplicationHelper
end

anything_but/app/views/activities/_do_not_want_activity.html.erb
<form>
    <div id="page-wrap">
        <div class="form-group">
          <br>
            <label class="control-label" for="inputDefault"> </label>
          <input type="text" class="form-control" id="do-not-want">
        </div>
        <button type="button" id="dnw-button" class="btn btn-default btn-lg btn-block">Go!</button>
        </form>
  </div>

anything_but/app/views/activities/_i_hate_that.html.erb
<form>
  <div id="result-wrapA">
  <button type="button" id="newRec" class="btn btn-default btn-lg btn-block">Next!</button>
</div>
</form>

anything_but/app/views/cities/_cities.html.erb
<%= form_for :city do |f|%>
  <%= f.label "Select Your City: "  %>
  <br>
  <%= f.collection_select :city_id, City.all, :id, :name %>
  <br>
  <%= f.submit "City Submit"%>
<% end %>

anything_but/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <ul class="breadcrumb">
    <li id="home-link-div"><a href="/" id="home-link"> Anything But </a></li>
    <% if !logged_in? %>
      <li><a href="/signin">Sign In</a></li>
      <li><a href="/signup">Sign Up</a></li>
    <% end %>
    <% if logged_in? %>
      <li><%= link_to current_user.username, dashboard_path %></a></li>
      <li><%= link_to "Log Out", signout_path %></a></li>
    <% end %>
  </ul>
    <%= yield %>
  </body>
</html>

anything_but/app/views/neighborhoods/_neighborhood.html.erb
<%= form_for :neighborhoods do |f|%>
  <%= f.label "Where Would You Go?"  %>
  <br>
  <%= f.collection_check_boxes :neighborhood_id, Neighborhood.all, :id, :name %>
  <br>
  <%= f.submit "Select Neighborhoods" %>
<% end %>

anything_but/app/views/recommendations/_recs.html.erb
<h3> You should go to </h3>

<h1><a href="<%= @recommendation.url%>" style="text-decoration: none;"><%= @recommendation.name %></a></h1>

anything_but/app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <p>Username:</p> <%= f.text_field :username %><br>
  <p>Password:</p> <%= f.password_field :password %><br>
  <p>Password Confirmation:</p> <%= f.password_field :password_confirmation %>
  <br>
  <br>
  <p><%= f.submit  "  Submit   " %></p>

<% end %>
 <br><br>

anything_but/app/views/users/edit.html.erb
<h1>Edit</h1>

<p><%= render "form" %></p>

anything_but/app/views/users/new.html.erb
<h1>Sign Up</h1>
<div id="signup">
<p><%= render "form"%></p>
</div>

anything_but/app/views/users/show.html.erb
<h2>Hello, <%= @user.username %></h1>
<br>
<body>

  <ul style="list-style: none;">
    <% @user.recommendations.each do |rec| %>
      <li class="liked_place"><p> <span class="glyphicon glyphicon-heart"></span>  <%= link_to rec.name, rec.url, :target => "_blank" %></span></p></li>
    <% end %>
  </ul>

  <br>
  <br>
  <%= link_to 'Delete Account', user_path(current_user), method: "delete" %>
</body>

anything_but/app/views/welcome/welcome.html.erb
<div id="location">
<p id="user-location"></p>
</div>
<div id="welcome-questions">
  <div id="page-wrapper">
    <h1> ANYTHING BUT</h1>
    <br>
    <h5 style="text-align: center">Type the name of a place you don't want to go ("Cinema", "Parks", etc), then choose the closest match and hit "Go"!</h5>
  </div>
  <div id="input-box" style="display: none;">
    <%= render 'activities/do_not_want_activity' %>
  </div>
</div>
<div id="page-wrapper">
  <div id="rec-response-div">
    <div id="response-wrapper">
    <h2 id="rec-response-h1"><h2>
    </div>
  </div>
</div>
<div class="col-md-4 col-md-offset-4" id="loading">
  <div class="spinner">
    <div class="sk-folding-cube">
      <div class="sk-cube1 sk-cube"></div>
      <div class="sk-cube2 sk-cube"></div>
      <div class="sk-cube4 sk-cube"></div>
      <div class="sk-cube3 sk-cube"></div>
    </div>
    <span style="right: -5px;">Loading</span>
  </div>
</div>
<div id="dislike-button" style="display: none;"><%= render "activities/i_hate_that" %><div>
  <div id="new-search-button" style="display: none;">
</div>
<div id="result-wrapB">
  <button style="button" class="btn btn-default btn-lg btn-block">New Search!</button>
</div>
<div id="like_button">
  <% if logged_in? %>
  <button type="button" class="btn btn-default btn-lg" align="center">
    <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
  </button>
  <% end %>
</div>